name: Integracion Continua Calculadora

# Esto le dice a GitHub que corra el workflow cada vez que hacen un push
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el código del repositorio
    - name: Checkout del código
      uses: actions/checkout@v3

    # Paso 2: Instalar Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Paso 3: Correr las pruebas que armaste
    - name: Ejecutar Pruebas Unitarias
      run: |
        python -m unittest test_calculadora.py
